# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'current_project',
                'verbose_name_plural': 'Current Project',
            },
        ),
        migrations.CreateModel(
            name='GroupProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('owner', models.BooleanField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'db_table': 'group_projects',
                'verbose_name_plural': 'Groups and Projects',
            },
        ),
        migrations.CreateModel(
            name='OG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'og',
                'verbose_name': 'OG',
                'verbose_name_plural': 'OGs',
            },
        ),
        migrations.CreateModel(
            name='TeamOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('og', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.OG')),
            ],
            options={
                'db_table': 'team_og',
                'verbose_name_plural': 'Team and OG',
            },
        ),
        migrations.AlterUniqueTogether(
            name='teamog',
            unique_together=set([('group',)]),
        ),
        migrations.AlterUniqueTogether(
            name='groupprojects',
            unique_together=set([('group', 'project')]),
        ),
    ]
